ALTER TABLE cities ADD COLUMN IF NOT EXISTS client_count INTEGER DEFAULT 0;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS session_count INTEGER DEFAULT 0;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS review_count INTEGER DEFAULT 0;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS whatsapp_number TEXT;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS whatsapp_message TEXT;
